Repository karafka/waterdrop, pull requests merged in 2024-06, with the labels that each got.

#499 Add topic scope to report_metric
  lib/waterdrop/instrumentation/vendors/datadog/metrics_listener.rb
  spec/lib/waterdrop/instrumentation/vendors/datadog/metrics_listener_spec.rb
Labels: enhancement

#503 Introduce `reload_on_transaction_fatal_error` to reload the librdkafka after transactional failures
  CHANGELOG.md
  config/locales/errors.yml
  lib/waterdrop/config.rb
  lib/waterdrop/contracts/config.rb
  lib/waterdrop/instrumentation/logger_listener.rb
  lib/waterdrop/instrumentation/notifications.rb
  lib/waterdrop/producer/transactions.rb
  spec/lib/waterdrop/contracts/config_spec.rb
  spec/lib/waterdrop/instrumentation/logger_listener_spec.rb
  spec/lib/waterdrop/producer/transactions_spec.rb
Labels: enhancement, transactions

#506 bump-deps-2024-06-17
  Gemfile.lock
Labels: dependencies

#509 bump-deps-2024-06-29
  Gemfile.lock
Labels: dependencies
