Repository karafka/waterdrop, pull requests merged in 2024-04, with the labels that each got.

#471 fix compose
  .github/workflows/ci.yml
Labels: internal, dependencies

#475 fix double middleware and double checks
  CHANGELOG.md
  lib/waterdrop/producer.rb
  lib/waterdrop/producer/buffer.rb
  spec/lib/waterdrop/producer/buffer_spec.rb
Labels: bug

#480 bump-deps-2024-04-19
  Gemfile.lock
Labels: dependencies

#481 Protect rdkafka thread from instrumentation crashes
  CHANGELOG.md
  lib/waterdrop/instrumentation/callbacks/delivery.rb
  lib/waterdrop/instrumentation/callbacks/error.rb
  lib/waterdrop/instrumentation/callbacks/oauthbearer_token_refresh.rb
  lib/waterdrop/instrumentation/callbacks/statistics.rb
  spec/lib/waterdrop/instrumentation/callbacks/delivery_spec.rb
  spec/lib/waterdrop/instrumentation/callbacks/error_spec.rb
  spec/lib/waterdrop/instrumentation/callbacks/oauthbearer_token_refresh_spec.rb
  spec/lib/waterdrop/instrumentation/callbacks/statistics_spec.rb
Labels: enhancement
